const menu = [
  {
    id: 1,
    title: 'Scrambled Eggs With Toast And Bacon',
    category: 'breakfast',
    price: 15.99,
    img: 'https://e-przepisykulinarne.pl/wp-content/uploads/2012/04/tost_boczek_jajko-1200x900.jpg',
    desc: `Golden scrambled eggs combined with crispy bacon and toast is a tasty and nutritious dish.`,
  },
  {
    id: 2,
    title: 'Burger with fries',
    category: 'lunch',
    price: 13.99,
    img: 'https://www.przyslijprzepis.pl/media/cache/big/uploads/media/recipe/0005/88/7090c2bfb5438fca6c393a263224b7988dcb1be7.jpeg',
    desc: `Cutlet, crispy vegetables and cheese, as well as golden fries create a combination.`,
  },
  {
    id: 3,
    title: 'Risotto With Shrimps And Asparagus',
    category: 'dinner',
    price: 6.99,
    img: 'https://i0.wp.com/blogzapetytem.pl/wp-content/uploads/2019/06/5B8F1E3C-B900-4A20-956B-847DDF0F9F9F.jpeg?fit=2048%2C1552&ssl=1',
    desc: `Risotto with shrimps and asparagus is an Italian dish`,
  },
  {
    id: 4,
    title: 'Chocolate Shake',
    category: 'shakes',
    price: 15.99,
    img: 'https://www.bestblender.pl/wp-content/uploads/2014/03/chocolatemilkshakemainjpg.jpg',
    desc: `Chocolate shake with whipped cream and pieces of cookies.`,
  },
  {
    id: 5,
    title: 'American Pancakes',
    category: 'breakfast',
    price: 17.99,
    img: 'https://maslove.pl/wp-content/uploads/2022/06/nalesniki-po-amerykansku-z-syropem-klonowym.jpg',
    desc: `American pancakes with maple syrup and fruit`,
  },
  {
    id: 6,
    title: 'Spaghetti carbonara',
    category: 'lunch',
    price: 18.99,
    img: 'https://www.allrecipes.com/thmb/0USVgLLUxe68kwcVRTe7ZVbWq6M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/11973-spaghetti-carbonara-II-mfs-044-6fb2128979334fe98c28064e75aa47c9.jpg',
    desc: `Spaghetti Carbonara is a classic Italian dish that consists of spaghetti pasta, eggs, bacon, Parmesan cheese and pepper.`,
  },
  {
    id: 7,
    title: 'Grilled Steak',
    category: 'dinner',
    price: 18.99,
    img: 'https://podravkaiovariations.azureedge.net/8d1ede48-640e-11eb-b3f1-0242ac120021/v/f2b1f6a6-64bc-11eb-b6c2-0242ac130010/1024x768-f2b21802-64bc-11eb-a115-0242ac130010.jpeg',
    desc: `Grilled steak with potatoes and vegetables `,
  },
  {
    id: 8,
    title: 'Strawberry Shake',
    category: 'shakes',
    price: 12.99,
    img: 'https://static.gotujmy.pl/ZDJECIE_PRZEPISU_ETAP/shake-truskawkowy-358511.jpg',
    desc: `Strawberry shake with vanilla ice cream and crumble`,
  },
  {
    id: 9,
    title: 'Belgian Waffles',
    category: 'breakfast',
    price: 13.99,
    img: 'https://f.wszelkieprzepisy.pl/images/4hf9bocr/gofry-belgijskie-orig.png',
    desc: `Belgian waffles with fruit and whipped cream`,
  },
  {
    id: 10,
    title: 'Chicken wirh rice ',
    category: 'lunch',
    price: 24.99,
    img: 'https://static.fajnegotowanie.pl/media/uploads/media_image/auto/recipe-content/1451/mobile/kurczak-tikka-masala.jpg',
    desc: `Chicken tikka masala with basmati rice.`,
  },
  {
    id: 11,
    title: 'Chicken with potatoes',
    category: 'dinner',
    price: 16.99,
    img: 'https://www.mniammniam.com/obrazki/kurczakpieczonyhcc7.jpg',
    desc: `Chicken in honey and mustard with baked potatoes and carrots`,
  },
  {
    id: 12,
    title: 'Blueberry Shake',
    category: 'shakes',
    price: 16.99,
    img: './images/menuSzejk1.png',
    desc: `Blueberry shake with soy milk and blueberry mousse.`,
  },
  {
    id: 13,
    title: 'Egg Croissant',
    category: 'breakfast',
    price: 8.99,
    img: 'http://2.bp.blogspot.com/-NB6nlS4ew8s/VL1KvgjfjOI/AAAAAAAAD20/nqe7jUCfE1A/s1600/IS_DSC_3016%2Bna%2Bbloga.jpg',
    desc: `Croissants with egg, ham and cheese are a tasty and nutritious choice.`,
  },
  {
    id: 14,
    title: 'Fillet with potatoes',
    category: 'lunch',
    price: 21.99,
    img: 'https://media.centrumrespo.pl/wp-content/uploads/2018/10/18002231/kurczakbok.png',
    desc: `Tagliatelle with shrimps and asparagus is an Italian dish in which a combination of shrimps and delicate asparagus.`,
  },
  {
    id: 15,
    title: 'Grilled Fillet',
    category: 'dinner',
    price: 13.99,
    img: 'https://static.gotujmy.pl/ZDJECIE_PRZEPISU_ETAP/grillowane-piersi-z-kurczaka-306228.jpg',
    desc: `Grilled chicken breast fillet with vegetables in the oven`,
  },
  {
    id: 16,
    title: 'Banana Shake',
    category: 'shakes',
    price: 16.99,
    img: 'https://malacukierenka.pl/wp-content/uploads/2011/05/shake-orzechowy-z-bananami.jpg',
    desc: `Banana shake with coconut milk and peanut butter`,
  },
];
export default menu;
